### ISSUE TITLE
PeerPad welcome page is gone

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/peerpad#329]
When entering https://peerpad.net, I no longer see the nice Welcome page it had once before

Also, the security disclaimer is gone. 

Can we have both back?

**Comment by jimpick** [comment]
All that has been in the plan since the spring ... it has been a victim of planning priorities. 

The only reason the current unfinished site is live is because the old version never worked well, and the new one was an improvement, and I launched it quickly so I could talk about it at the IPFS Meetup in Barcelona... it was clear that if we waited for everything we wanted, it wasn’t going to launch. Looking forward, it’s not clear how I can get development cycle time on it beyond maintenance in my extra time ... hopefully it gets some OKR love some time in the future.

**Comment by daviddias** [comment]
Understood. I believe that the welcome page is a good to have and that the security banner is a must have. If you were to estimate the amount of time necessary to bring those 2 back, how many hours/days would you say?

**Comment by jimpick** [comment]
That's a tough question ...

On the face of it, it should only take a few hours to make some HTML changes.

After discussion with @parkan, who was doing project management at the time, the welcome page was removed very intentionally so it could be replaced with something that better tells the current narrative. Initially, we were going to scale the project up as peer-base became something we were going to sink major development time into, but then it unexpectedly got scaled to zero. I liked some elements of the original landing page, but it overpromised and was a bad fit with the current state of the project.

I personally did not like the implementation of the security banner... I strongly feel it missed an opportunity. It did not attempt to educate users about the security model (which is actually a huge improvement over traditional web applications) - it's function was to scare and bounce users.

I feel that the current needs of the project are to move the project to a footing where it is readily able to accept volunteer community contributions, and is less dependent on continuous PL-funded developer time. That's a different narrative, and a different landing page. The education component might be better accomplished by integrating the landing page experience deeply into the UI of the "app" instead of masking off the app with a static layout.

**Comment by parkan** [comment]
very well put @jimpick!

I stand by the decision to remove the landing page, both at that time (when the intent was to make a lean tool to dogfood and iterate) and as a broader product decision. See #303, #304 and https://github.com/ipfs-shipyard/pm-peer-pad/issues/35 for rationale.

I do agree that we need an explanatory notice/experimental warning and CTA for potential contributors, the way we discussed doing this was by linking out to a blog post. The perpetually uncertain fate of the project has been the main blocker.

@jimpick: I could take a day sometime in the next couple of weeks to help out with this if you want to give it a try?
