### ISSUE TITLE
Status message never changes to "online"

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/peerpad#58]
Possible cause: if IPFS is already online the started event will never be fired, and component state never updated

https://github.com/ipfs-shipyard/peerpad-core/blob/master/src/network.js#L10
https://github.com/ipfs-shipyard/peerpad/blob/master/src/components/Edit.js#L216

**Comment by pgte** [comment]
@alanshaw good catch.

Since the back-end is an app-wide singleton, we need to store that state.
On top of the `started` event, `peerpad-core` now has a [`.network.hasStarted()` method](https://github.com/ipfs-shipyard/peerpad-core#backendnetworkhasstarted).

You'll need to upgrade to `peerpad-core` v0.5.0 to be able to use this.

**Comment by olizilla** [comment]
@pgte I'll wire this up. Just to check, I should be testing `.network.hasStarted()` to see if our node is already running, and if not, listen once for `started`.

In the UI, should we be representing the started status as **Online** rather than **Started** ?

**Comment by pgte** [comment]
> @pgte I'll wire this up. Just to check, I should be testing .network.hasStarted() to see if our node is already running, and if not, listen once for started.

Correct.

> In the UI, should we be representing the started status as Online rather than Started ?

Yes, "Online" sounds better.
