### ISSUE TITLE
Sometimes random full deletions happen

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/peerpad#97]
I've noticed this 3-4 times now, but cannot reproduce it. Sometimes when i've just loaded a pad, and i started writing, it will suddenly delete everything.

One time, _i think (but cannot confirm)_ such a deletion propagated through to other peerpad instances (i had 3 open).

**Comment by nicola** [comment]
It happened to me at the very beginning as well.
If you type as soon as the pad is created (eager typer bug)

**Comment by pgte** [comment]
It's probably because of a race condition due to eager typing.
Quick fix is to have input disabled before online.

**Comment by nicola** [comment]
Tell me if I am wrong, but ideally, I should still be able to make changes while "offline" and then once I am back on my changes should propagate

**Comment by pgte** [comment]
Yes, of course it should :)
I only think this is related to the time of deletion (initialising the content to an empty string), which I think Y.js is marking as an operation, in relation to the time of getting remote state..

**Comment by pgte** [comment]
I think I understand what's going on.
Codemirror is active before Y.js is ready.
Once Y.js is ready we bind codemirror, overriding any use value code mirror may already have.
I think the fix here is to only allow input in codemirror once the CRDT is initialized, otherwise that content input meanwhile gets obliterated.
Special attention must be given so that the CRDT is considered initialized independently of node being online or not because, as @nicola said, the user should be able to start editing offline and then join the network.
